from beautifullogger.beautifullogger import setup, setDisplayLevel
from beautifullogger.beautifullogger import test
from beautifullogger.beautifullogger import getCounter, addCounter
from beautifullogger.beautifullogger import getStderrHandler, getLogHandler
